# Generated by Django 5.2.11 on 2026-02-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0004_product_description_product_sku_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='SmartStock Pro', max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
