# Generated by Django 5.2.11 on 2026-02-25 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0005_storesettings_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='customer',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
